import * as fs from 'fs';
import * as path from 'path';

// This file is auto-generated by the Builder.
// Do not edit manually if possible.

const LOG_ROOT_RELATIVE = "__LOG_ROOT_RELATIVE_PATH__";
const SERVICE_NAME = "__SERVICE_NAME__";

const STATE = {
  initialized: false,
  logRoot: "",
};

function init() {
  if (STATE.initialized) return;
  
  // Resolve absolute path to logs
  STATE.logRoot = path.resolve(__dirname, LOG_ROOT_RELATIVE);
  
  // Ensure service directory exists
  const serviceLogDir = path.join(STATE.logRoot, SERVICE_NAME);
  if (!fs.existsSync(serviceLogDir)) {
    try {
      fs.mkdirSync(serviceLogDir, { recursive: true });
    } catch (e) {
      console.error("Failed to create log directory:", serviceLogDir, e);
    }
  }
  
  STATE.initialized = true;
}

export function log(message: string, level: 'info' | 'error' | 'warn' = 'info') {
  if (!STATE.initialized) init();

  const timestamp = new Date().toISOString();
  // Simple YYYY-MM-DD log rotation
  const dateStr = timestamp.split('T')[0];
  const logFile = path.join(STATE.logRoot, SERVICE_NAME, `${dateStr}.log`);
  
  const logLine = `[${timestamp}] [${level.toUpperCase()}] ${message}\n`;

  // Console output
  if (level === 'error') console.error(message);
  else console.log(message);

  // File output
  try {
    fs.appendFileSync(logFile, logLine);
  } catch (e) {
    // Fallback if filesystem fails
    console.error("Failed to write to log file:", e);
  }
}
